services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://admin:adminpassword123@mongo:27017/qna_db?authSource=admin
    restart: unless-stopped
    networks:
      - mynetwork

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        BACKEND_URL: http://localhost:5000
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - mynetwork

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
        MONGO_INITDB_ROOT_USERNAME: admin
        MONGO_INITDB_ROOT_PASSWORD: adminpassword123
    restart: unless-stopped
    networks:
      - mynetwork

volumes:
  data:

networks:
  mynetwork:
    driver: bridge  # <-- Explicitly setting driver
